---
title: Customize
---

## Edit and add your pages

Each page should start with 
```
---
title: your title
---
```
and the first header will be the 2nd level, so `## `. Note, there are situations where you leave off
```
---
title: your title
---
```
and start the qmd file with a level header `# `, but if using the default title yaml (in the `---` fence) is a good habit since it makes it easy for Quarto convert your qmd file to other formats (like into a presentation).

## Add a chunk of code describing your setup

Case study files should include:

* R version
* TMB version
* FIMS commit
* Name of your stock
* Name of your region
* Name of the analyst

Please ensure that both the [`DESCRIPTION`](https://github.com/NOAA-FIMS/case-studies/blob/main/DESCRIPTION) and [`.github/workflows/render-and-publish.yml`](https://github.com/NOAA-FIMS/case-studies/blob/main/.github/workflows/render-and-publish.yml#L20C7-L21C124) files are updated if the case study requires the installation of additional R packages.

Please use the following code to load the required packages within each case study:
```{r}
# Names of required CRAN packages
packages <- c("TMB")

# Load packages
invisible(lapply(packages, library, character.only = TRUE))

library(FIMS)
library(TMBhelper)
```

To render the bookdown product locally, please run devtools::install_deps() to install all dependencies listed in the [`DESCRIPTION`](https://github.com/NOAA-FIMS/case-studies/blob/main/DESCRIPTION) file. 

## Add a bulleted list and script describing simplifications you had to make

How I simplified my assessment
* Remove seasonality
* etc.

## Add your script that sets up and runs the model

## Add your comparison figures

## Add comparison tables

## What was your experience using FIMS? What could we do to improve usability?

## List any issues that you ran into or found

Please [open an issue](https://github.com/NOAA-FIMS/FIMS/issues/new/choose) if you found something new.

## What features are most important to add based on this case study?

## Add your pages to the project

* Add the files to `_quarto.yml`
